In [1]:
import os
import sys
if os.path.abspath('..') not in sys.path:
    sys.path.insert(0, os.path.abspath('..'))
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from plotly.subplots import make_subplots
from lattices import Lattice, Catalogue, plotting

In [2]:
nodal_positions = [
    [0,0,0],
    [1,0,0],
    [0,1,0],
    [0,0,1],
    [1,1,0],
    [1,0,1],
    [0,1,1],
    [1,1,1]
]
edge_adjacency = [
    [0,1],
    [0,2],
    [0,3],
    [1,4],
    [1,5],
    [2,4],
    [2,6],
    [3,5],
    [3,6],
    [4,7],
    [5,7],
    [6,7]
]
lat = Lattice(nodal_positions=nodal_positions, edge_adjacency=edge_adjacency)
plotting.plotly_unit_cell_3d(lat).show()

The possible node types that lattice can have are:
- inner
- face
- edge
- corner

In [3]:
lat.calculate_node_types()

{'corner_nodes': {0, 1, 2, 3, 4, 5, 6, 7},
 'edge_nodes': set(),
 'face_nodes': set(),
 'inner_nodes': set()}

Windowed representation is such that all nodes are of *inner* type

In [4]:
lat_w = lat.create_windowed(min_edge_length=0.2)
plotting.plotly_unit_cell_3d(lat_w, show_uc_box=True).show()
lat_w.calculate_node_types()

{'corner_nodes': set(),
 'edge_nodes': set(),
 'face_nodes': {0, 1, 2, 4, 5, 6},
 'inner_nodes': {3}}

Fundamental representation is one in which all nodes are inner nodes and their tesselations

In [5]:
lat_w.calculate_fundamental_representation()
plotting.plotly_unit_cell_3d(lat_w, show_uc_box=True, repr='fundamental').show()
print(lat_w)
print('Fundamental node coordinates: ', lat_w.transformed_node_coordinates[np.unique(lat_w.fundamental_edge_adjacency)])
print('Fundamental tesselation vectors:\n', lat_w.fundamental_tesselation_vecs)

{'num_nodes': 7, 'num_edges': 6, 'num_fundamental_nodes': 1, 'num_fundamental_edges': 3}
Fundamental node coordinates:  [[0.68414 0.26581 0.22874]]
Fundamental tesselation vectors:
 [[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [6]:
cat = Catalogue.from_file('./sample_cat.lat', 0)

Some lattices have overlapping struts. Here is how we can fix it

In [7]:
lat_dict = cat[1]
lat = Lattice(**lat_dict)
lat.name = 'With intersections'
fig = make_subplots(rows=1, cols=2, specs=[[{'type':'scatter3d'}, {'type':'scatter3d'}]], subplot_titles=['Original', 'Windowed'])
fig = plotting.plotly_unit_cell_3d(lat, fig=fig, subplot={'index':0, 'ncols':2})
edge_points = lat.find_edge_intersections()
lat.split_edges_by_points(edge_points)
lat.name = 'Split at intersections'
plotting.plotly_unit_cell_3d(lat, fig=fig, subplot={'index':1, 'ncols':2}).show()

Tesselate unit cell

In [8]:
lat_tess = lat.create_tesselated(2,2,2)
lat_tess.name = 'Tesselated'
plotting.plotly_unit_cell_3d(lat_tess, show_uc_box=True).show()